version: '2.2'
services:
  web:
    build: .
    ports:
      - "13361:5000"
    cpus: 0.1
    mem_limit: 128M
    restart: on-failure
  redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"
      cpus: 0.1
      mem_limit: 128M
      restart: on-failure
